Documenting the project (Readme) and it's behaviour (Diagrams)
CSCfi/HPCS pull request #13
Opened 2024-03-25 13:18 UTC by telliere

- [ ] Readme 
   - [x]  Quickstart
     - [x] Client
     - [ ] Server
   - [x] Limitations

 - [x] CLI

 - [x] Architecture
   - [x] Global Architecture
   - [x] Sequence Diagrams
     - [x] Data preparation
     - [x] Container preparation
     - [x] Job preparation
   - [ ] Token lifecycle - Permissions

2024-03-27 10:54 UTC, mmatthiesencsc commented
Hi Emilien, thanks a lot for this very detailed documentation, really good work! I suggest we have a quick look through it face2face, but please feel free to accept the suggestions that are easy to accept and don't need discussion.

2024-03-27 11:15 UTC, telliere commented
I don't have any suggestion on the PR

2024-03-27 11:24 UTC, mmatthiesencsc requested changes

2024-03-27 11:44 UTC, telliere commented on docs/architecture/container_preparation.md
> +    Container Preparation container ->> Container Preparation container: Parse info file based on previous steps
Encryption / Preparation isn't part of the process here, it's encapsulated in "Prepare container, results in an encrypted image and a private key (see below)" -> Reference to sequence diagrams coming after, explaining the prepare & encrypt process

2024-03-27 11:48 UTC, telliere commented
Thank you very much for the review @mmatthiesencsc. Really valuable to me. Applied every recommandations after reviewing them

2024-04-05 14:43 UTC, telliere commented
Last bits of documentation are here, a last review should allow us to merge this branch @mmatthiesencsc

2024-04-08 07:26 UTC, mmatthiesencsc approved these changes
Thanks Emilien, merging as last state of your efforts this time. I have not yet tested the installation.

2024-04-08 07:26 UTC, merged